server:
  port: ${port.codebox-boot-admin}

spring:
  application:
    name: codebox-boot-admin
  profiles:
    active: local
  config:
    import: "optional:configserver:http://codebox-cloud-config"
  banner:
    location: classpath:/banner/banner.txt

management:
  endpoints:
    web:
      exposure:
        include: '*'

---
spring:
  config:
    activate:
      on-profile: local
    import: "optional:configserver:http://127.0.0.1:8500"

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: stag

---
spring:
  config:
    activate:
      on-profile: prod